name: build-wheels-macos-arm64

on:
  push:
    branches:
      - wheel
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: build-wheels-macos-arm64-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels_macos_arm64:
    name: ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        python-version: ["cp38", "cp39", "cp310", "cp311", "cp312", "cp313"]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: "${{ matrix.python-version}}-* "
          CIBW_ENVIRONMENT: KALDI_NATIVE_FBANK_CMAKE_ARGS="-DCMAKE_OSX_ARCHITECTURES='arm64'"
          CIBW_ARCHS: "arm64"
          CIBW_BUILD_VERBOSITY: 3

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        shell: bash
        run: |
          opts='--break-system-packages'
          v=${{ matrix.python-version }}
          if [[ $v == cp38 || $v == cp39 ]]; then
            opts=''
          fi

          python3 -m pip install $opts --upgrade pip
          python3 -m pip install $opts wheel twine==5.0.0 setuptools

          twine upload ./wheelhouse/*.whl
