name: windows-x64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: windows-x64-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows_x64:
    name: Test on Win64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -D CMAKE_BUILD_TYPE=Release ..

      - name: Build kaldi-native-fbank for windows
        shell: bash
        run: |
          cd build
          cmake --build . --target ALL_BUILD --config Release
          cat CMakeCache.txt

      - name: Run tests for windows
        shell: bash
        run: |
          cd build
          ctest --verbose -C Release --output-on-failure -E py

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip pytest
          python3 -m pip install wheel twine setuptools

      - name: Build Python
        shell: bash
        run: |
          python3 -m pip install --verbose .

      - name: Display Python package version
        shell: bash
        run: |
          python3 -c "import kaldi_native_fbank; print(kaldi_native_fbank.__version__)"
          python3 -c "import kaldi_native_fbank; print(kaldi_native_fbank.__file__)"

      - name: Run Python tests
        shell: bash
        run: |
          cd kaldi-native-fbank/python/tests
          python3 ./test_fbank_options.py
          python3 ./test_frame_extraction_options.py
          python3 ./test_mel_bank_options.py
