name: windows-x86

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: windows-x86-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows_x86:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.vs-version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - vs-version: vs2015
            toolset-version: v140
            os: windows-2019

          - vs-version: vs2017
            toolset-version: v141
            os: windows-2019

          - vs-version: vs2019
            toolset-version: v142
            os: windows-2022

          - vs-version: vs2022
            toolset-version: v143
            os: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -T ${{ matrix.toolset-version}},host=x64 -A Win32 -D CMAKE_BUILD_TYPE=Release -DKALDI_NATIVE_FBANK_BUILD_PYTHON=OFF ..
          cat CMakeCache.txt


      - name: Build kaldi-native-fbank for windows
        shell: bash
        run: |
          cd build
          cmake --build . --target ALL_BUILD --config Release

      - name: Run tests for windows
        shell: bash
        run: |
          cd build

          ctest --verbose -C Release --output-on-failure -E py
